## Creating and using numpy arrays

Here are several ways to create NumPy arrays:

1. **Using `np.array`:** You can create a NumPy array from a Python list or tuple using the `np.array()` function.

```python
import numpy as np

# Create a 1-dimensional array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  # Output: [1 2 3 4 5]

# Create a 2-dimensional array from a nested list
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# Output:
# [[1 2 3]
#  [4 5 6]]
```

2. **Using `np.zeros`:** You can create an array filled with zeros using the `np.zeros` function. Specify the shape of the array as a tuple or an integer value.

```python
import numpy as np

# Create a 1-dimensional array of length 5 filled with zeros
arr1 = np.zeros(5)
print(arr1)  # Output: [0. 0. 0. 0. 0.]

# Create a 2-dimensional array of shape (3, 4) filled with zeros
arr2 = np.zeros((3, 4))
print(arr2)
# Output:
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]
```

3. **Using `np.ones`:** You can create an array filled with ones using the `np.ones` function. It takes the same arguments as `np.zeros`.

```python
import numpy as np

# Create a 1-dimensional array of length 3 filled with ones
arr1 = np.ones(3)
print(arr1)  # Output: [1. 1. 1.]

# Create a 2-dimensional array of shape (2, 3) filled with ones
arr2 = np.ones((2, 3))
print(arr2)
# Output:
# [[1. 1. 1.]
#  [1. 1. 1.]]
```

4. **Using `np.full`:** You can create an array filled with a specified value using `np.full`.

```python
import numpy as np

# Create a 1-dimensional array of length 3 filled with the value 5
arr = np.full(3, 5)
print(arr)
# Output: [5 5 5]
```

5. **Using `np.eye`:** You can create an identity matrix using `np.eye`.

```python
import numpy as np

I = np.eye(3)
print(I)
# Output:
# [[1 0 0],
#  [0 1 0], 
#  [0 0 1]]
```

6. **Using `np.arange`:** You can create a 1-dimensional array with a range of values using the `np.arange` function, similar to the built-in `range` function.

```python
import numpy as np

# Create a 1-dimensional array with values from 0 to 4
arr1 = np.arange(5)
print(arr1)  # Output: [0 1 2 3 4]

# Create a 1-dimensional array with values from 2 to 10 with a step of 2
arr2 = np.arange(2, 11, 2)
print(arr2)  # Output: [ 2  4  6  8 10]
```

7. **Using `np.linspace`:** You can create a 1-dimensional array with a specified number of evenly spaced values within a range using the `np.linspace` function.

```python
import numpy as np

# Create a 1-dimensional array with 5 values from 0 to 1 (inclusive)
arr1 = np.linspace(0, 1, 5)
print(arr1)  # Output: [0.   0.25 0.5  0.75 1.  ]

# Create a 1-dimensional array with 9 values from 1 to 10 (inclusive)
arr2 = np.linspace(1, 10, 9)
print(arr2)  # Output: [ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]
```

### `np.array` function:

In NumPy, the `np.array` function is used to create a new array object. It takes an input sequence, such as a list or tuple, and returns a NumPy array that represents the same data.

Here's how `np.array` works:

1. **Input:** You provide a sequence-like object as an argument to `np.array`. This can be a Python list, tuple, or any other iterable object.

1. **Data Type Inference:** NumPy automatically infers the data type of the elements in the input sequence. It selects a common data type that can represent all the elements accurately. For example, if the input sequence contains integers and floating-point numbers, the resulting array's data type will be floating-point.

1. **Array Creation:** The `np.array` function creates a new NumPy array object based on the input sequence. The array object is an N-dimensional array with a fixed shape and data type.

1. **Array Attributes:** The resulting array has several important attributes, including the shape, dtype (data type), and size (number of elements). These attributes provide information about the structure and characteristics of the array.

Here's an example that demonstrates the usage of `np.array`:

```python
import numpy as np

# Create a NumPy array from a list
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)
# Output: [1 2 3 4 5]

print(my_array.shape)
# Output: (5,)

print(my_array.dtype)
# Output: int64

print(my_array.size)
# Output: 5
```

In the above example, `np.array(my_list)` creates a NumPy array from the Python list `my_list`. The resulting array `my_array` contains the same elements as the input list. The `shape` attribute indicates that it is a 1-dimensional array with a length of 5. The `dtype` attribute shows that the array's elements have the data type `int64`. Finally, the `size` attribute reveals that the array contains 5 elements.

By using `np.array`, you can convert Python sequences into NumPy arrays, enabling you to perform efficient numerical computations, leverage NumPy's extensive functionality, and take advantage of optimized operations on arrays.

In [13]:
import numpy as np

# Create a 1-dimensional array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)  # Output: [1 2 3 4 5]

print(f'array 1: {arr1} , shape: {arr1.shape}, size: {arr1.size}, dtype: {arr1.dtype}')

print('_______\n')

# Create a 2-dimensional array from a nested list
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f'array 2: \n {arr2} \n , shape: {arr2.shape}, size: {arr2.size}, dtype: {arr2.dtype}')

[1 2 3 4 5]
array 1: [1 2 3 4 5] , shape: (5,), size: 5, dtype: int64
_______

array 2: 
 [[1 2 3]
 [4 5 6]] 
 , shape: (2, 3), size: 6, dtype: int64


> **You can specify `dtype` when creating a numpy array**

In [14]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.float32)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float32


### `np.zeros` function:

In NumPy, the `np.zeros` function is used to create an array filled with zeros. It allows you to create an array of a specified shape and data type, where all the elements are initialized to zero.

The general syntax of `np.zeros` is:

```python
np.zeros(shape, dtype=float, order='C')
```

Here's what each parameter means:

- `shape`: It specifies the shape of the array you want to create. It can be an integer or a tuple of integers. For example, if you pass `(2, 3)`, it creates a 2-dimensional array with 2 rows and 3 columns.
- `dtype` (optional): It specifies the data type of the elements in the array. By default, it is set to `float`. You can provide other data types like `int`, `bool`, etc.
- `order` (optional): It specifies the memory layout of the array. It can be `'C'` for row-major (C-style) or `'F'` for column-major (Fortran-style). By default, it is set to `'C'`.

Here's an example that demonstrates the usage of `np.zeros`:

```python
import numpy as np

# Create a 1-dimensional array of length 5 filled with zeros
arr1 = np.zeros(5)
print(arr1)
# Output: [0. 0. 0. 0. 0.]

# Create a 2-dimensional array with 3 rows and 4 columns filled with zeros
arr2 = np.zeros((3, 4))
print(arr2)
# Output:
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]

# Create a 3-dimensional array with shape (2, 3, 2) filled with zeros
arr3 = np.zeros((2, 3, 2), dtype=int)
print(arr3)
# Output:
# [[[0 0]
#   [0 0]
#   [0 0]]
#
#  [[0 0]
#   [0 0]
#   [0 0]]]
```

In the examples above, `np.zeros` is used to create arrays of different shapes and data types, and all the elements in the arrays are initialized to zero.

In [18]:
import numpy as np

arr1 = np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [19]:
arr2 = np.zeros((3, 4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### `np.ones` function:

In NumPy, the `np.ones` function is used to create an array filled with ones. It allows you to create an array of a specified shape and data type, where all the elements are initialized to one.

The general syntax of `np.ones` is:

```python
np.ones(shape, dtype=None, order='C')
```

Here's what each parameter means:

- `shape`: It specifies the shape of the array you want to create. It can be an integer or a tuple of integers. For example, if you pass `(2, 3)`, it creates a 2-dimensional array with 2 rows and 3 columns.
- `dtype` (optional): It specifies the data type of the elements in the array. By default, it is set to `float`. You can provide other data types like `int`, `bool`, etc.
- `order` (optional): It specifies the memory layout of the array. It can be `'C'` for row-major (C-style) or `'F'` for column-major (Fortran-style). By default, it is set to `'C'`.

Here's an example that demonstrates the usage of `np.ones`:

```python
import numpy as np

# Create a 1-dimensional array of length 5 filled with ones
arr1 = np.ones(5)
print(arr1)
# Output: [1. 1. 1. 1. 1.]

# Create a 2-dimensional array with 3 rows and 4 columns filled with ones
arr2 = np.ones((3, 4))
print(arr2)
# Output:
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

# Create a 3-dimensional array with shape (2, 3, 2) filled with ones of integer type
arr3 = np.ones((2, 3, 2), dtype=int)
print(arr3)
# Output:
# [[[1 1]
#   [1 1]
#   [1 1]]
#
#  [[1 1]
#   [1 1]
#   [1 1]]]
```

In the examples above, `np.ones` is used to create arrays of different shapes and data types, and all the elements in the arrays are initialized to one.

In [20]:
import numpy as np

arr1 = np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [21]:
arr2 = np.ones((3, 4))
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### `np.full` function

In NumPy, the `np.full` function is used to create a new array with a specified shape and fill it with a given value. The syntax of the `np.full` function is as follows:

```python
numpy.full(shape, fill_value, dtype=None, order='C')
```

Let's break down the parameters:

- `shape`: This parameter specifies the shape of the output array. It can be an integer or a tuple of integers representing the dimensions of the array.
- `fill_value`: This parameter specifies the value that will be filled in all the elements of the output array.
- `dtype` (optional): This parameter specifies the data type of the elements in the output array. If not provided, it will be determined automatically based on the `fill_value`.
- `order` (optional): This parameter specifies the order of the elements in the output array. It can be either 'C' for row-major order or 'F' for column-major order. By default, it is set to 'C'.

Here's an example to illustrate the usage of `np.full`:

```python
import numpy as np

# Create a 2x3 array filled with 5
arr = np.full((2, 3), 5)

print(arr)
```

Output:

```
[[5 5 5]
 [5 5 5]]
```

In this example, `np.full((2, 3), 5)` creates a 2x3 array where all the elements are filled with the value 5.

You can also provide a data type explicitly by setting the `dtype` parameter. For example:

```python
arr = np.full((2, 2), 3.14, dtype=float)
```

This creates a 2x2 array filled with the value 3.14, and the data type of the array is explicitly set to `float`.

In [22]:
import numpy as np

arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


### `np.eye` function

In NumPy, the `np.eye` function is used to create a 2-dimensional array with ones on the diagonal and zeros elsewhere. This function returns an identity matrix. The syntax of the `np.eye` function is as follows:

```python
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
```

Let's break down the parameters:

- `N`: This parameter specifies the number of rows in the output array.
- `M` (optional): This parameter specifies the number of columns in the output array. If not provided, it defaults to `N`.
- `k` (optional): This parameter specifies the index of the diagonal. A zero value (default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value refers to a lower diagonal.
- `dtype` (optional): This parameter specifies the data type of the elements in the output array. It is set to `float` by default.
- `order` (optional): This parameter specifies the order of the elements in the output array. It can be either 'C' for row-major order or 'F' for column-major order. By default, it is set to 'C'.

Here's an example to illustrate the usage of `np.eye`:

```python
import numpy as np

# Create a 3x3 identity matrix
arr = np.eye(3)

print(arr)
```

Output:

```
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
```

In this example, `np.eye(3)` creates a 3x3 identity matrix where the diagonal elements are ones and the off-diagonal elements are zeros.

You can also specify the index of the diagonal using the `k` parameter. For example:

```python
arr = np.eye(4, k=1)

print(arr)
```

Output:

```
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
```

In this example, `np.eye(4, k=1)` creates a 4x4 matrix where the diagonal one position above the main diagonal is filled with ones, and the rest of the elements are zeros.

In [27]:
import numpy as np

arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
arr = np.eye(3, 2)

print(arr)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [29]:
arr = np.eye(4, k=1)

print(arr)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


### `arange` function

The `np.arange` function in NumPy is used to create an array of evenly spaced values within a specified range. It is similar to the Python built-in `range` function but returns an array instead of a list.

The general syntax of `np.arange` is as follows:

```python
np.arange(start, stop, step, dtype=None)
```

The parameters of the `np.arange` function are as follows:

- `start`: It specifies the start value of the sequence (inclusive). If not provided, the default value is 0.
- `stop`: It specifies the end value of the sequence (exclusive). This value is required.
- `step`: It specifies the step or the spacing between the values in the sequence. If not provided, the default step is 1.
- `dtype`: It specifies the data type of the elements in the array. If not provided, it is automatically inferred based on the other input arguments.

The `np.arange` function returns a 1-dimensional NumPy array containing the values within the specified range. The array includes the `start` value and stops before reaching the `stop` value. The `step` parameter determines the spacing between the values.

Here's an example to illustrate the usage of `np.arange`:

```python
import numpy as np

# Create an array from 0 to 9 (exclusive) with step 1
arr1 = np.arange(10)
print(arr1)
# Output: [0 1 2 3 4 5 6 7 8 9]

# Create an array from 1 to 10 (exclusive) with step 2
arr2 = np.arange(1, 10, 2)
print(arr2)
# Output: [1 3 5 7 9]

# Create an array from 5 to 1 (exclusive) with step -1
arr3 = np.arange(5, 0, -1)
print(arr3)
# Output: [5 4 3 2 1]
```

In the examples above, `np.arange` is used to create arrays with different start, stop, and step values. The resulting arrays contain the specified sequence of values within the given range.

In [35]:
import numpy as np

arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
arr2 = np.arange(1, 10, 2)
print(arr2)

[1 3 5 7 9]


In [37]:
arr3 = np.arange(5, 0, -1)
print(arr3)

[5 4 3 2 1]


### `np.linspace` function

The `np.linspace` function in NumPy is used to create an array of evenly spaced values over a specified interval. It is similar to `np.arange()` but instead of specifying the step value, you provide the number of elements you want in the array.

The general syntax of `np.linspace` is as follows:

```python
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
```

The parameters of the `np.linspace` function are as follows:

- `start`: It specifies the start value of the sequence (inclusive). This value is required.
- `stop`: It specifies the end value of the sequence (inclusive). This value is required.
- `num`: It specifies the number of elements you want in the array. By default, it is set to 50.
- `endpoint`: It determines whether the `stop` value should be included in the array. If `True`, the `stop` value is included. If `False`, the `stop` value is excluded. By default, it is set to `True`.
- `retstep`: It determines whether to return the step value used in the sequence. If `True`, it returns the step value along with the array. By default, it is set to `False`.
- `dtype`: It specifies the data type of the elements in the array. If not provided, it is inferred based on the other input arguments.

The `np.linspace` function returns a 1-dimensional NumPy array containing the specified number of evenly spaced values over the interval. The values in the array are inclusive of both the `start` and `stop` values (unless `endpoint=False`).

Here's an example to illustrate the usage of `np.linspace`:

```python
import numpy as np

# Create an array with 5 evenly spaced values from 0 to 1 (inclusive)
arr1 = np.linspace(0, 1, num=5)
print(arr1)
# Output: [0.   0.25 0.5  0.75 1.  ]

# Create an array with 10 values from 1 to 5 (inclusive)
arr2 = np.linspace(1, 5, num=10)
print(arr2)
# Output: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
#          3.66666667 4.11111111 4.55555556 5.        ]

# Create an array with 3 values from 0 to 100 (inclusive), excluding the endpoint
arr3 = np.linspace(0, 100, num=3, endpoint=False)
print(arr3)
# Output: [ 0.  50. 100.]
```

In the examples above, `np.linspace` is used to create arrays with different start, stop, and num values. The resulting arrays contain the specified number of evenly spaced values within the given interval.

In [39]:
import numpy as np

arr1 = np.linspace(0, 1, num=5)
print(arr1)

[0.   0.25 0.5  0.75 1.  ]


In [40]:
arr2 = np.linspace(1, 5, num=10)
print(arr2)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [43]:
arr3 = np.linspace(0, 100, num=3, endpoint=False)
print(arr3)

[ 0.         33.33333333 66.66666667]
