## NumPy `random` sub-module

The NumPy library provides a sub-module called numpy.random that offers a wide range of functions for generating random numbers and arrays. The numpy.random module is commonly used for tasks such as random sampling, generating random numbers from various probability distributions, and shuffling arrays.

Certainly! Here's a list of some commonly used functions from the `numpy.random` sub-module along with examples of how to use them:

1. **`random()`**: Generates random numbers from a uniform distribution between 0 and 1.

   ```python
   import numpy as np

   # Generate a random number between 0 and 1
   random_number = np.random.random()
   print(random_number)
   ```

1. **`rand(d1, d2, ..., dn)`**: Generates an array of random numbers from a uniform distribution between 0 and 1 with a specified shape.

   ```python
   import numpy as np

   # Generate a 3x3 array of random numbers between 0 and 1
   random_array = np.random.rand(3, 3)
   print(random_array)
   ```

1. **`randn(d1, d2, ..., dn)`**: Generates an array of random numbers from a standard normal distribution (mean 0, standard deviation 1) with a specified shape.

   ```python
   import numpy as np

   # Generate a 2x2 array of random numbers from a standard normal distribution
   random_array = np.random.randn(2, 2)
   print(random_array)
   ```

1. **`randint(low, high=None, size=None, dtype=int)`**: Return random integers from `low` (inclusive) to `high` (exclusive).

   ```python
   import numpy as np

   # Generate a 3*3 matrix with random integer between 0 and 9
   random_integer = np.random.randint(0, 10, size=(3,3))
   print(random_integer)
   ```

1. **`normal(mean, std, size)`**: Generates random numbers from a normal (Gaussian) distribution with a specified mean and standard deviation.

   ```python
   import numpy as np

   # Generate a 3*3 matrix with random numbers from a normal distribution with mean 0 and standard deviation 1
   random_numbers = np.random.normal(0, 1, size=(3, 3))
   print(random_numbers)
   ```

1. **`shuffle(x)`**: Randomly shuffles the elements of an array in-place.

   ```python
   import numpy as np

   # Shuffle the elements of an array
   array = np.array([1, 2, 3, 4, 5])
   np.random.shuffle(array)
   print(array)
   ```

1. **`seed(s)`**: Sets the seed for the random number generator to ensure reproducibility.

   ```python
   import numpy as np

   # Set the seed to ensure reproducibility
   np.random.seed(42)

   # Generate a random number
   random_number = np.random.random()
   print(random_number)
   ```


These are just a few examples of the many functions available in the `numpy.random` sub-module. Each function provides different functionalities for generating random numbers, arrays, and samples from various distributions.

### `random` function

The `np.random.random()` function is a part of the `numpy.random` sub-module in NumPy. It generates random numbers from a continuous uniform distribution over the interval \[0, 1). In other words, it generates random floating-point numbers between 0 (inclusive) and 1 (exclusive).

The `np.random.random()` function takes an optional argument `size` that specifies the shape of the output. It can be a single integer or a tuple of integers. If `size` is not provided, a single random number is returned.

Here's an example:

```python
import numpy as np

# Generate a single random number
random_number = np.random.random()
print(random_number)

# Generate a 2x2 array of random numbers
random_array = np.random.random((2, 2))
print(random_array)
```

In this example, the first `np.random.random()` call generates a single random number between 0 and 1, and the result is printed.

The second `np.random.random()` call generates a 2x2 array of random numbers. The shape `(2, 2)` is passed as the `size` argument, indicating that we want a 2x2 array. The resulting array contains four random numbers between 0 and 1, and it is printed.

The `np.random.random()` function is useful when you need random numbers uniformly distributed between 0 and 1, which can be handy for various purposes such as simulations, statistical modeling, or generating random data for testing or experimentation.

In [4]:
import numpy as np

random_number = np.random.random()
print(random_number)

0.11680416084314582


In [5]:
random_array = np.random.random((2, 2))
print(random_array)

[[0.34114572 0.72801972]
 [0.29362045 0.55885409]]


### `rand` function

The `np.random.rand` function is another function provided by the `numpy.random` sub-module in NumPy. It generates random numbers from a uniform distribution over the interval \[0, 1) with a specified shape.

The `np.random.rand` function takes one or more arguments to define the shape of the output. Each argument represents the size of a dimension in the output array. Alternatively, you can pass a tuple of integers to specify the shape.

Here's an example:

```python
import numpy as np

# Generate a single random number
random_number = np.random.rand()
print(random_number)

# Generate a 2x2 array of random numbers
random_array = np.random.rand(2, 2)
print(random_array)
```

In this example, the first `np.random.rand()` call generates a single random number between 0 and 1, and the result is printed.

The second `np.random.rand()` call generates a 2x2 array of random numbers. The arguments `(2, 2)` indicate that we want a 2x2 array. The resulting array contains four random numbers between 0 and 1, and it is printed.

It's important to note that the `np.random.rand()` function generates random numbers from a uniform distribution over the interval \[0, 1), which means that all the generated numbers are equally likely within that range.

The `np.random.rand()` function is commonly used when you need random numbers uniformly distributed between 0 and 1 with a specific shape, such as when creating random arrays for simulations, initializing weights in machine learning models, or generating random data for various applications.

In [6]:
import numpy as np

random_number = np.random.rand()
print(random_number)

0.5309707613953903


In [7]:
random_array = np.random.rand(2, 2)
print(random_array)

[[0.32566559 0.36185299]
 [0.43130371 0.45130751]]


### `randn` function

The `np.random.randn` function is another function provided by the `numpy.random` sub-module in NumPy. It generates random numbers from a standard normal distribution, also known as a Gaussian distribution or a bell curve, with a mean of 0 and a standard deviation of 1.

The `np.random.randn` function takes one or more arguments to define the shape of the output. Each argument represents the size of a dimension in the output array. Alternatively, you can pass a tuple of integers to specify the shape.

Here's an example:

```python
import numpy as np

# Generate a single random number
random_number = np.random.randn()
print(random_number)

# Generate a 2x2 array of random numbers
random_array = np.random.randn(2, 2)
print(random_array)
```

In this example, the first `np.random.randn` call generates a single random number from a standard normal distribution, and the result is printed.

The second `np.random.randn` call generates a 2x2 array of random numbers. The arguments `(2, 2)` indicate that we want a 2x2 array. The resulting array contains four random numbers drawn from a standard normal distribution, and it is printed.

The key characteristic of the standard normal distribution is that it has a symmetric bell-shaped curve centered around the mean of 0. The majority of the generated random numbers will be close to 0, with decreasing probability as the values move away from 0.

The `np.random.randn` function is commonly used when you need random numbers from a standard normal distribution with a specific shape. It is often utilized in simulations, statistical modeling, generating random data for experimentation or testing, and various other applications that involve random numbers following a Gaussian distribution.

### `normal` function

The `np.random.normal` function is a part of the `numpy.random` sub-module in NumPy. It generates random numbers from a normal (Gaussian) distribution with a specified mean and standard deviation.

The `np.random.normal` function takes three arguments: `loc`, `scale`, and `size`.

- The `loc` argument represents the mean of the distribution.
- The `scale` argument represents the standard deviation of the distribution.
- The `size` argument (optional) specifies the shape of the output array.

Here's an example:

```python
import numpy as np

# Generate a single random number from a normal distribution with mean 0 and standard deviation 1
random_number = np.random.normal(loc=0, scale=1)
print(random_number)

# Generate a 2x2 array of random numbers from a normal distribution with mean 2 and standard deviation 0.5
random_array = np.random.normal(loc=2, scale=0.5, size=(2, 2))
print(random_array)
```

In this example, the first `np.random.normal` call generates a single random number from a normal distribution with a mean of 0 and a standard deviation of 1. The resulting number is printed.

The second `np.random.normal` call generates a 2x2 array of random numbers from a normal distribution with a mean of 2 and a standard deviation of 0.5. The `size` argument `(2, 2)` is passed to specify the shape of the output array. The resulting array contains four random numbers drawn from the specified normal distribution, and it is printed.

The normal distribution is a continuous probability distribution that is symmetric and bell-shaped. It is widely applicable in various fields, particularly in statistics and probability theory, due to its prevalence in natural phenomena and the Central Limit Theorem.

The `np.random.normal` function is frequently used when you need random numbers from a normal distribution with specific mean and standard deviation values. It is useful for various tasks such as generating random data for statistical modeling, simulating real-world phenomena, and conducting experiments and simulations.

In [8]:
import numpy as np

random_number = np.random.normal(loc=0, scale=1)
print(random_number)

-1.4567457272000583


In [9]:
random_array = np.random.normal(loc=2, scale=0.5, size=(2, 2))
print(random_array)

[[2.66568673 2.11026167]
 [1.65262564 1.35765353]]
