## NumPy matrix operations

NumPy provides several matrix operations that allow you to perform mathematical operations on matrices efficiently. Here are some commonly used NumPy matrix operations with examples:

1. Matrix Multiplication: You can perform matrix multiplication using the `numpy.matmul` function or the `@` operator.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.matmul(A, B)        # Matrix multiplication using np.matmul()
D = A @ B                  # Matrix multiplication using @ operator
```
The resulting matrix `C` and `D` will be:
```python
[[19 22]
 [43 50]]
```

2. Element-wise Matrix Operations: NumPy allows you to perform element-wise matrix operations such as addition, subtraction, multiplication, and division. These operations are performed on corresponding elements of the matrices.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B                  # Element-wise addition
D = A - B                  # Element-wise subtraction
E = A * B                  # Element-wise multiplication
F = A / B                  # Element-wise division
```
The resulting matrices `C`, `D`, `E`, and `F` will be:
```python
[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
```

3. Transpose: You can obtain the transpose of a matrix using the `numpy.transpose` function or the `.T` attribute.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.transpose(A)       # Transpose using np.transpose()
C = A.T                   # Transpose using .T attribute
```
The resulting matrices `B` and `C` will be:
```python
[[1 3]
 [2 4]]
```

4. Inverse: You can compute the inverse of a matrix using the `numpy.linalg.inv()` function.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.linalg.inv(A)      # Compute the inverse of A
```
The resulting matrix `B` will be:
```python
[[-2.   1. ]
 [ 1.5 -0.5]]
```

5. Determinant: You can compute the determinant of a matrix using the `numpy.linalg.det()` function.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])

det = np.linalg.det(A)    # Compute the determinant of A
```
The resulting determinant value will be:
```python
-2.0
```

These are just a few examples of the many matrix operations that NumPy provides. NumPy's matrix operations enable efficient computation and manipulation of matrices in various scientific and numerical applications.

### Matrix Multiplication

Matrix multiplication in NumPy is performed using the `numpy.matmul` function or the `@` operator.

The `numpy.matmul` function takes two arrays as input and returns their matrix product. It follows the rules of matrix multiplication, where the number of columns in the first matrix must be equal to the number of rows in the second matrix.

Here's an example of matrix multiplication using `numpy.matmul`:

```python
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.matmul(A, B)
```

The resulting matrix `C` will be:

```python
[[ 58  64]
 [139 154]]
```

Alternatively, you can use the `@` operator for matrix multiplication in NumPy, which provides a more concise way of performing the operation:

```python
C = A @ B
```

The result will be the same as the previous example.

It's important to note that matrix multiplication is different from element-wise multiplication (`*`). Matrix multiplication follows specific rules for calculating the resulting matrix dimensions and element values based on the corresponding elements of the input matrices.

Matrix multiplication is a fundamental operation in linear algebra and is widely used in various scientific and mathematical computations, including solving systems of linear equations, transforming coordinates, and performing data transformations in machine learning.

In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.matmul(A, B)

C

array([[ 58,  64],
       [139, 154]])

In [2]:
A @ B

array([[ 58,  64],
       [139, 154]])