## NumPy matrix operations

NumPy provides several matrix operations that allow you to perform mathematical operations on matrices efficiently. Here are some commonly used NumPy matrix operations with examples:

1. **Matrix Multiplication:** You can perform matrix multiplication using the `numpy.matmul` function or the `@` operator.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.matmul(A, B)        # Matrix multiplication using np.matmul()
D = A @ B                  # Matrix multiplication using @ operator
```
The resulting matrix `C` and `D` will be:
```python
[[19 22]
 [43 50]]
```

2. **Element-wise Matrix Operations:** NumPy allows you to perform element-wise matrix operations such as addition, subtraction, multiplication, and division. These operations are performed on corresponding elements of the matrices.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B                  # Element-wise addition
D = A - B                  # Element-wise subtraction
E = A * B                  # Element-wise multiplication
F = A / B                  # Element-wise division
```
The resulting matrices `C`, `D`, `E`, and `F` will be:
```python
[[ 6  8]
 [10 12]]

[[-4 -4]
 [-4 -4]]

[[ 5 12]
 [21 32]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
```

3. **Transpose:** You can obtain the transpose of a matrix using the `numpy.transpose` function or the `.T` attribute.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.transpose(A)       # Transpose using np.transpose()
C = A.T                   # Transpose using .T attribute
```
The resulting matrices `B` and `C` will be:
```python
[[1 3]
 [2 4]]
```

4. **Inverse:** You can compute the inverse of a matrix using the `numpy.linalg.inv()` function.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.linalg.inv(A)      # Compute the inverse of A
```
The resulting matrix `B` will be:
```python
[[-2.   1. ]
 [ 1.5 -0.5]]
```

5. **Determinant:** You can compute the determinant of a matrix using the `numpy.linalg.det()` function.
```python
import numpy as np

A = np.array([[1, 2], [3, 4]])

det = np.linalg.det(A)    # Compute the determinant of A
```
The resulting determinant value will be:
```python
-2.0
```

These are just a few examples of the many matrix operations that NumPy provides. NumPy's matrix operations enable efficient computation and manipulation of matrices in various scientific and numerical applications.

### Matrix Multiplication

Matrix multiplication in NumPy is performed using the `numpy.matmul` function or the `@` operator.

The `numpy.matmul` function takes two arrays as input and returns their matrix product. It follows the rules of matrix multiplication, where the number of columns in the first matrix must be equal to the number of rows in the second matrix.

Here's an example of matrix multiplication using `numpy.matmul`:

```python
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.matmul(A, B)
```

The resulting matrix `C` will be:

```python
[[ 58  64]
 [139 154]]
```

Alternatively, you can use the `@` operator for matrix multiplication in NumPy, which provides a more concise way of performing the operation:

```python
C = A @ B
```

The result will be the same as the previous example.

It's important to note that matrix multiplication is different from element-wise multiplication (`*`). Matrix multiplication follows specific rules for calculating the resulting matrix dimensions and element values based on the corresponding elements of the input matrices.

Matrix multiplication is a fundamental operation in linear algebra and is widely used in various scientific and mathematical computations, including solving systems of linear equations, transforming coordinates, and performing data transformations in machine learning.

In [3]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = np.matmul(A, B)

C

array([[ 58,  64],
       [139, 154]])

In [2]:
A @ B

array([[ 58,  64],
       [139, 154]])

### Element-wise Matrix Operations

Element-wise matrix operations in NumPy refer to performing operations on corresponding elements of two or more matrices. In other words, the operation is applied independently to each element, pairing the elements with the same indices. This behavior is also known as element-wise broadcasting.

NumPy provides a wide range of mathematical functions and operators that can be applied element-wise to matrices. Some common element-wise operations include addition, subtraction, multiplication, division, exponentiation, and comparison.

Here's an example to illustrate element-wise operations in NumPy:

```python
import numpy as np

# Create two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise addition
C = A + B
# C = [[1+5, 2+6],
#      [3+7, 4+8]]
# C = [[6, 8],
#      [10, 12]]

# Element-wise subtraction
D = A - B
# D = [[1-5, 2-6],
#      [3-7, 4-8]]
# D = [[-4, -4],
#      [-4, -4]]

# Element-wise multiplication
E = A * B
# E = [[1*5, 2*6],
#      [3*7, 4*8]]
# E = [[5, 12],
#      [21, 32]]

# Element-wise division
F = A / B
# F = [[1/5, 2/6],
#      [3/7, 4/8]]
# F = [[0.2, 0.333],
#      [0.428, 0.5]]

# Element-wise exponentiation
G = A ** B
# G = [[1^5, 2^6],
#      [3^7, 4^8]]
# G = [[1, 64],
#      [2187, 65536]]

# Element-wise comparison
H = A > B
# H = [[1>5, 2>6],
#      [3>7, 4>8]]
# H = [[False, False],
#      [False, False]]
```

In the above example, each operation is performed element-wise on the corresponding elements of matrices A and B, resulting in a new matrix with the same shape as the input matrices.

Element-wise operations are a fundamental feature of NumPy and are particularly useful when working with large arrays or matrices, as they allow for efficient computation without the need for explicit loops.

In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [2]:
C = A + B
C

array([[ 6,  8],
       [10, 12]])

In [3]:
D = A - B
D

array([[-4, -4],
       [-4, -4]])

In [5]:
E = A * B
E

array([[ 5, 12],
       [21, 32]])

In [6]:
F = A / B
F

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [7]:
G = A ** B
G

array([[    1,    64],
       [ 2187, 65536]])

In [8]:
H = A > B
H

array([[False, False],
       [False, False]])

### Transpose

Matrix transpose is an operation that flips a matrix over its diagonal, resulting in a new matrix where the rows of the original matrix become the columns and vice versa. In other words, if A is an m x n matrix, then the transpose of A, denoted as A^T, is an n x m matrix.

The transpose operation is often used in linear algebra and matrix computations. It can be helpful for various purposes such as solving systems of linear equations, performing matrix operations, and representing data in a different format.

In NumPy, the transpose of a matrix can be obtained using the `.T` attribute or the `numpy.transpose()` function. Here's an example:

```python
import numpy as np

# Create a matrix
A = np.array([[1, 2, 3], [4, 5, 6]])

# Get the transpose using .T attribute
A_transpose = A.T

# Get the transpose using numpy.transpose() function
A_transpose = np.transpose(A)

print("Original matrix:")
print(A)
print("Transpose matrix:")
print(A_transpose)
```

Output:
```python
Original matrix:
[[1 2 3]
 [4 5 6]]

Transpose matrix:
[[1 4]
 [2 5]
 [3 6]]
```

In the above example, we create a 2x3 matrix `A`. The transpose of `A` is obtained using both the `.T` attribute and the `numpy.transpose()` function, and the result is stored in the variable `A_transpose`. Finally, we print the original matrix and its transpose.

Both methods produce the same result, which is the transpose of the original matrix `A`. The rows of the original matrix become the columns in the transpose, and the columns become the rows. So, the original matrix has dimensions 2x3, and its transpose has dimensions 3x2.

In [9]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])

A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

### Inverse

In linear algebra, the inverse of a square matrix $A$ is a matrix denoted as $A^{-1}$, such that when $A$ is multiplied by its inverse, the result is the identity matrix (denoted as $I$). In other words, if $A$ is an $n \times n$ matrix and $A^{-1}$ is its inverse, then $A^{-1}$ satisfies the equation $A^{-1} \times A = A \times A^{-1} = I$.

The concept of matrix inverse is useful in many areas of mathematics and engineering, including solving systems of linear equations, computing determinants, and performing transformations. However, not all matrices have inverses. Only square matrices that are non-singular (also called invertible or non-degenerate) have inverses.

In NumPy, you can compute the inverse of a matrix using the `numpy.linalg.inv()` function. Here's an example:

```python
import numpy as np

# Create a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Original matrix:")
print(A)
print("Inverse matrix:")
print(A_inv)
```

Output:
```python
Original matrix:
[[1 2]
 [3 4]]
 
Inverse matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]
```

In the above example, we create a $2 \times 2$ square matrix `A`. The inverse of `A` is computed using the `numpy.linalg.inv()` function, and the result is stored in the variable `A_inv`. Finally, we print the original matrix and its inverse.

The computed inverse matrix `A_inv` satisfies the property that `A * A_inv` (or `A_inv * A`) is approximately equal to the identity matrix `I`. Due to numerical precision, the inverse may contain small floating-point errors.

It's important to note that not all matrices have inverses. If a matrix is singular (i.e., its determinant is zero), it does not have an inverse. In such cases, attempting to compute the inverse using `numpy.linalg.inv()` will raise a `LinAlgError`.

In [11]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

A_inv = np.linalg.inv(A)

print("Original matrix:")
print(A)
print("Inverse matrix:")
print(A_inv)

Original matrix:
[[1 2]
 [3 4]]
Inverse matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
A @ A_inv

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

> **Note that due to some computational instability the result of `A @ A_inv` is not exactly identity matrix but is very close to it**

### Determinant

In linear algebra, the determinant of a square matrix is a scalar value that provides important information about the properties of the matrix. The determinant is denoted as $det(A)$ or $|A|$, where $A$ is the matrix.

The determinant is a useful quantity in various areas of mathematics and engineering. It has applications in solving systems of linear equations, computing matrix inverses, analyzing transformations, and determining the linear independence of vectors.

In NumPy, you can compute the determinant of a matrix using the `numpy.linalg.det()` function. Here's an example:

```python
import numpy as np

# Create a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the determinant
det_A = np.linalg.det(A)

print("Matrix:")
print(A)
print("Determinant:", det_A)
```

Output:
```
Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0
```

In the above example, we create a 2x2 matrix `A`. The determinant of `A` is computed using the `numpy.linalg.det()` function, and the result is stored in the variable `det_A`. Finally, we print the original matrix and its determinant.

The computed determinant value provides information about the matrix. For example, if the determinant is zero, the matrix is singular and does not have an inverse. If the determinant is non-zero, the matrix is non-singular and has an inverse. Additionally, the magnitude of the determinant can indicate the scaling factor of the matrix transformation.

In [13]:
import numpy as np

# Create a square matrix
A = np.array([[1, 2], [3, 4]])

# Compute the determinant
det_A = np.linalg.det(A)

print("Matrix:")
print(A)
print("Determinant:", det_A)

Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004
