## NumPy Indexing

Indexing in NumPy is the process of accessing elements or sub-arrays of a NumPy array.

* **Indexing starts at 0.** This means that the first element of a NumPy array has index 0, the second element has index 1, and so on.
* **Negative indexing is supported.** Negative indices can be used to access elements from the end of the array. For example, `arr[-1]` refers to the last element of the array `arr`.
* **Multiple dimensions are supported.** NumPy arrays can be multi-dimensional, which means that they can have more than one axis. To index an element in a multi-dimensional array, you specify the index for each axis. For example, to index the element at the first row and second column of a 2D array, you would use the expression `arr[0, 1]`.

Here are the different types of indexing supported by NumPy, along with an example for each:

* **Single element indexing:** This type of indexing allows you to access a single element in the array. The index can be an integer, a slice, or a Boolean array.

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Single element indexing
print(arr[0])  # Prints 1
print(arr[-1])  # Prints 5
print(arr[2])  # Prints 3
```

* **Slicing:** This type of indexing allows you to access a sub-array of the array. The slice is specified using a colon (:) separated by the start, stop, and step indices. The start and stop indices are optional, and the default values are 0 and the length of the array, respectively. The step index is also optional, and the default value is 1.

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Slicing
print(arr[1:3])  # Prints [2, 3]
print(arr[2:])  # Prints [3, 4, 5]
print(arr[:2])  # Prints [1, 2]
```

* **Boolean indexing:** This type of indexing allows you to access elements that meet a certain condition. The condition is specified using a Boolean array, where each element in the array is either True or False. The elements in the array that correspond to True values in the Boolean array will be selected.

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Boolean indexing
print(arr[arr > 3])  # Prints [4, 5]
```

* **Fancy indexing:** This type of indexing allows you to access elements based on their index values. The index values can be any iterable object, such as a list, a tuple, or a NumPy array.

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Fancy indexing
print(arr[[1, 3]])  # Prints [2, 4]
```

I hope this list is helpful. Let me know if you have any other questions.

In addition to the above, there are also a few other types of indexing supported by NumPy, such as:


For more information on NumPy indexing, please refer to the [NumPy documentation](https://numpy.org/doc/stable/user/basics.indexing.html).

Here is a table summarizing the different types of indexing supported by NumPy:

| Type | Description |
|---|---|
| Single element indexing | Accesses a single element in the array. |
| Slicing | Accesses a sub-array of the array. |
| Boolean indexing | Accesses elements that meet a certain condition. |
| Fancy indexing | Accesses elements based on their index values. |

### Single element indexing

Single element indexing in NumPy works the same for 1D and ND arrays. The only difference is that for ND arrays, you need to specify the index for each dimension of the array.

Here is an example of single element indexing with a 1D array:

```python
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

# Single element indexing
print(arr[0])    # 1
print(arr[-1])    # 5
```

The output of the above code is:

```
1
5
```

As you can see, the first line of code prints the first element of the array, which is 1. The second line prints the last element of the array, which is 5.

Here is an example of single element indexing with a 2D array:

```python
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Single element indexing
print(arr[0, 0])    # 1
print(arr[1, 2])    # 6
```

The output of the above code is:

```
1
6
```

As you can see, the first line of code prints the element at the first row and first column of the array, which is 1. The second line prints the element at the second row and third column of the array, which is 6.

Here are some additional things to keep in mind about single element indexing in NumPy with ND arrays:

* The index for each dimension must be within the bounds of the array. If you try to access an element that is out of bounds, you will get an error.
* You can use negative indices to access elements from the end of the array. For example, to access the last element of the first row of a 2D array, you would use the index `arr[0, -1]`.
* You can use slice objects to access a range of elements from an array. For example, to access the first two elements of the first row of a 2D array, you would use the slice object `arr[0, :2]`.

In [3]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d[0])
print(arr_1d[-1])

1
5


In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2d[0, 0])
print(arr_2d[0, 2])

1
3


### Slicing

Slicing in NumPy arrays works by specifying a range of elements to be included. The range is specified using a slice object, which is a tuple of integers. The slice object can have three elements:

* The start index: The index of the first element to be included.
* The stop index: The index of the last element to be included.
* The step size: The number of elements to skip between each element.

If the start index is not specified, it is assumed to be 0. If the stop index is not specified, it is assumed to be the end of the array. If the step size is not specified, it is assumed to be 1.

Here are some examples of slicing with ND NumPy arrays:

* Slicing a 2D array by rows:

```python
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Slicing the first row
print(arr[0, :])    # [1 2 3]

# Slicing the second row
print(arr[1, :])    # [4 5 6]
```

* Slicing a 2D array by columns:

```python
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Slicing the first column
print(arr[:, 0])    # [1 4]

# Slicing the second column
print(arr[:, 1])    # [2 5]
```

* Slicing a 3D array by planes:

```python
import numpy as np

# Create a 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Slicing the first plane
print(arr[0, :, 1:])    # [[2 3]
                        #  [5 6]]

```

* Slicing a multidimensional array with mixed slices:

```python
import numpy as np

# Create a 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Slicing the first two rows and the first two columns
print(arr[0:2, :2, :])    # [[1 2 3]
                          #  [4 5 6]]
```

Here are some additional things to keep in mind about slicing in NumPy arrays:

* The start index and stop index must be integers.
* The step size can be an integer or a negative integer.
* If the step size is negative, the elements will be sliced in reverse order.
* You can use slice objects to slice elements from a multidimensional array. In this case, the slice object must be a tuple of integers, where each integer specifies the slice for a particular dimension of the array.
* Slicing is a very common operation in NumPy. It is used to access a subset of elements from an array, to iterate over an array, and to perform other operations on arrays.

This image can help you visualize slicing in multi-dimensions in NumPy:

<img src="./imgs/np_array.png" width="600" height="200">

In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0, :])
print(arr[1, :])

[1 2 3]
[4 5 6]


In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[:, 0])
print(arr[:, 1])

[1 4]
[2 5]


In [14]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, :, 1:]) 

[[2 3]
 [5 6]]


In [20]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0:2, :2, :])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Boolean Indexing

Boolean indexing in NumPy is a technique that allows you to select elements from an array based on a boolean condition or a boolean mask. It involves using an array of boolean values to specify which elements of the array should be accessed or manipulated.

Here's an example to illustrate boolean indexing in NumPy:

``` python
import numpy as np

# Create a 1-dimensional array
arr = np.array([10, 20, 30, 40, 50])

# Create a boolean mask based on a condition
mask = arr > 30

# Access elements based on the boolean mask
selected_elements = arr[mask]

print(selected_elements)
```

Output:
```python
[40 50]
```

In this example, we create a 1-dimensional array `arr`. We then define a boolean mask `mask` by applying the condition `arr > 30`, which evaluates to `[False, False, False, True, True]`. The mask indicates which elements of `arr` satisfy the condition.

By using the boolean mask as an index array, we can select the elements from `arr` where the mask is `True`. In this case, the elements at indices 3 and 4 (corresponding to values 40 and 50) satisfy the condition and are selected.

Boolean indexing is particularly useful when you want to select elements from an array based on a certain criterion or condition. The condition used to create the boolean mask can involve mathematical operations, logical operators, or even more complex expressions. It provides a flexible and efficient way to filter and manipulate array data in NumPy.

In [24]:
arr = np.array([10, 20, 30, 40, 50])
arr[[True, False, False, True, False]]

array([10, 40])

In [26]:
arr > 30

array([False, False, False,  True,  True])

In [25]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mask = arr > 30

selected_elements = arr[mask]

print(selected_elements)

[40 50]


### Fancy Indexing

In NumPy, fancy indexing is a technique that allows you to access or manipulate array elements using arrays of indices or boolean masks. It provides a powerful way to select elements from an array based on certain criteria or patterns. Fancy indexing can be done using arrays, lists, or boolean arrays as indexing objects.

Here are a few examples to illustrate fancy indexing in NumPy:

Example 1: Indexing with arrays
``` python
import numpy as np

# Create a 1-dimensional array
arr = np.array([10, 20, 30, 40, 50])

# Create an array of indices
indices = np.array([1, 3])

# Access elements at specified indices
selected_elements = arr[indices]

print(selected_elements)
```
Output:
```python
[20 40]
```
In this example, we create a 1-dimensional array `arr` and an array of indices `indices`. By using `indices` as an index array, we can select the elements at indices 1 and 3 from the original array `arr`.

Example 2: Indexing with multidimensional arrays
``` python
import numpy as np

# Create a 2-dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create an array of row indices
row_indices = np.array([0, 2])

# Create an array of column indices
col_indices = np.array([1, 2])

# Access elements at specified row and column indices
selected_elements = arr[row_indices, col_indices]

print(selected_elements)
```
Output:
```python
[2 9]
```
In this example, we create a 2-dimensional array `arr` and arrays of row indices `row_indices` and column indices `col_indices`. By using these index arrays, we can select specific elements from the original array `arr` based on the corresponding row and column indices.

These examples demonstrate how fancy indexing can be used to select specific elements from NumPy arrays based on indices or boolean masks. Fancy indexing provides a flexible and efficient way to perform complex operations on arrays.

In [22]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

indices = np.array([1, 3])

selected_elements = arr[indices]

print(selected_elements)

[20 40]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_indices = np.array([0, 2])

col_indices = np.array([1, 2])

selected_elements = arr[row_indices, col_indices]

print(selected_elements)

[2 9]
