## Stacking

In NumPy, stacking refers to the process of combining arrays along a new axis. It allows you to concatenate arrays horizontally (column-wise) or vertically (row-wise) to create a new array with a higher dimension. NumPy provides several functions for stacking arrays, including `hstack` and `vstack`.

1. **`numpy.hstack`**: This function is used to horizontally stack arrays. It takes a sequence of arrays as input and returns a new array formed by stacking them horizontally. The arrays must have the same shape along all dimensions except the one being stacked. Here's an example:

```python
import numpy as np

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

result = np.hstack((array_1, array_2))
print(result)
```

Output:
```
[1 2 3 4 5 6]
```

In this example, the `hstack` function horizontally stacks `array1` and `array2` to create a new array `[1, 2, 3, 4, 5, 6]`.

2. **`numpy.vstack`**: This function is used to vertically stack arrays. It takes a sequence of arrays as input and returns a new array formed by stacking them vertically. Again, the arrays must have the same shape along all dimensions except the one being stacked. Here's an example:

```python
import numpy as np

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

result = np.vstack((array_1, array_2))
print(result)
```

Output:
```
[[1 2 3]
 [4 5 6]]
```

In this example, the `vstack` function vertically stacks `array1` and `array2` to create a new 2D array `[[1, 2, 3], [4, 5, 6]]`.

Both `hstack` and `vstack` functions are useful when you want to combine arrays either horizontally or vertically. They provide a convenient way to concatenate arrays and create higher-dimensional arrays.

In [7]:
import numpy as np

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

np.hstack((array_1, array_2))

array([1, 2, 3, 4, 5, 6])

In [8]:
np.vstack((array_1, array_2))

array([[1, 2, 3],
       [4, 5, 6]])

> **The arrays must have the same shape along all dimensions except the one being stacked, for `htstack` it only sencond dimension can differ.**

In [32]:
matrix_1 = np.random.randint(0, 10, (3,4))
matrix_2 = np.random.randint(0, 10, (3, 5))

In [33]:
matrix_1

array([[1, 6, 5, 0],
       [9, 7, 8, 5],
       [6, 4, 1, 6]])

In [34]:
matrix_2

array([[1, 4, 3, 3, 4],
       [1, 3, 5, 2, 9],
       [4, 5, 2, 7, 9]])

In [35]:
np.hstack((matrix_1, matrix_2))

array([[1, 6, 5, 0, 1, 4, 3, 3, 4],
       [9, 7, 8, 5, 1, 3, 5, 2, 9],
       [6, 4, 1, 6, 4, 5, 2, 7, 9]])

> **The arrays must have the same shape along all dimensions except the one being stacked, for `vtstack` it only first dimension can differ.**

In [36]:
matrix_1 = np.random.randint(0, 10, (5, 4))
matrix_2 = np.random.randint(0, 10, (3, 4))

In [37]:
matrix_1

array([[7, 5, 5, 8],
       [5, 1, 8, 6],
       [2, 7, 8, 2],
       [6, 7, 8, 5],
       [0, 1, 8, 0]])

In [38]:
matrix_2

array([[9, 7, 1, 5],
       [4, 1, 7, 7],
       [9, 3, 3, 7]])

In [39]:
np.vstack((matrix_1, matrix_2))

array([[7, 5, 5, 8],
       [5, 1, 8, 6],
       [2, 7, 8, 2],
       [6, 7, 8, 5],
       [0, 1, 8, 0],
       [9, 7, 1, 5],
       [4, 1, 7, 7],
       [9, 3, 3, 7]])