## Stacking

In NumPy, stacking refers to the process of combining arrays along a new axis. It allows you to concatenate arrays horizontally (column-wise) or vertically (row-wise) to create a new array with a higher dimension. NumPy provides several functions for stacking arrays, including `hstack` and `vstack`.

1. **`numpy.hstack`**: This function is used to horizontally stack arrays. It takes a sequence of arrays as input and returns a new array formed by stacking them horizontally. The arrays must have the same shape along all dimensions except the one being stacked. Here's an example:

```python
import numpy as np

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

result = np.hstack((array_1, array_2))
print(result)
```

Output:
```
[1 2 3 4 5 6]
```

In this example, the `hstack` function horizontally stacks `array1` and `array2` to create a new array `[1, 2, 3, 4, 5, 6]`.

2. **`numpy.vstack`**: This function is used to vertically stack arrays. It takes a sequence of arrays as input and returns a new array formed by stacking them vertically. Again, the arrays must have the same shape along all dimensions except the one being stacked. Here's an example:

```python
import numpy as np

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

result = np.vstack((array_1, array_2))
print(result)
```

Output:
```
[[1 2 3]
 [4 5 6]]
```

In this example, the `vstack` function vertically stacks `array1` and `array2` to create a new 2D array `[[1, 2, 3], [4, 5, 6]]`.

Both `hstack` and `vstack` functions are useful when you want to combine arrays either horizontally or vertically. They provide a convenient way to concatenate arrays and create higher-dimensional arrays.

In [7]:
import numpy as np

array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

np.hstack((array_1, array_2))

array([1, 2, 3, 4, 5, 6])

In [8]:
np.vstack((array_1, array_2))

array([[1, 2, 3],
       [4, 5, 6]])

> **The arrays must have the same shape along all dimensions except the one being stacked, for `htstack` it only sencond dimension can differ.**

In [32]:
matrix_1 = np.random.randint(0, 10, (3,4))
matrix_2 = np.random.randint(0, 10, (3, 5))

In [33]:
matrix_1

array([[1, 6, 5, 0],
       [9, 7, 8, 5],
       [6, 4, 1, 6]])

In [34]:
matrix_2

array([[1, 4, 3, 3, 4],
       [1, 3, 5, 2, 9],
       [4, 5, 2, 7, 9]])

In [35]:
np.hstack((matrix_1, matrix_2))

array([[1, 6, 5, 0, 1, 4, 3, 3, 4],
       [9, 7, 8, 5, 1, 3, 5, 2, 9],
       [6, 4, 1, 6, 4, 5, 2, 7, 9]])

> **The arrays must have the same shape along all dimensions except the one being stacked, for `vtstack` it only first dimension can differ.**

In [36]:
matrix_1 = np.random.randint(0, 10, (5, 4))
matrix_2 = np.random.randint(0, 10, (3, 4))

In [37]:
matrix_1

array([[7, 5, 5, 8],
       [5, 1, 8, 6],
       [2, 7, 8, 2],
       [6, 7, 8, 5],
       [0, 1, 8, 0]])

In [38]:
matrix_2

array([[9, 7, 1, 5],
       [4, 1, 7, 7],
       [9, 3, 3, 7]])

In [39]:
np.vstack((matrix_1, matrix_2))

array([[7, 5, 5, 8],
       [5, 1, 8, 6],
       [2, 7, 8, 2],
       [6, 7, 8, 5],
       [0, 1, 8, 0],
       [9, 7, 1, 5],
       [4, 1, 7, 7],
       [9, 3, 3, 7]])

### `np.concatenate` a more general function

The `np.concatenate` function in NumPy is used to concatenate or join arrays along a specified axis. It allows you to combine multiple arrays into a single array by appending them along the specified axis.

The syntax of the `np.concatenate` function is as follows:

```python
np.concatenate((array1, array2, ...), axis=0)
```

Here, `array1`, `array2`, and so on, are the arrays that you want to concatenate. The `axis` parameter specifies the axis along which the concatenation should take place. By default, `axis=0`, which means the arrays are concatenated along the first dimension (rows). You can change the value of `axis` to concatenate the arrays along other dimensions.

Here's an example to illustrate the usage of `np.concatenate`:

```python
import numpy as np

# Create two arrays
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate the arrays along the rows (axis=0)
result = np.concatenate((array_1, array_2), axis=0)
print(result)
```

Output:
```
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
```

In this example, `array1` and `array2` are concatenated along the rows (axis=0) using `np.concatenate`. The resulting array `result` contains all the rows from `array1` followed by all the rows from `array2`.

Some important points to note about `np.concatenate`:

- The arrays being concatenated must have the same shape along the specified axis. For example, if concatenating along axis=0, the arrays should have the same number of columns.

- `np.concatenate` can be used to concatenate arrays of any dimension, not just 2D arrays. The shape of the arrays along the non-concatenating axes should be the same.

- If the arrays being concatenated have different shapes along the specified axis, a `ValueError` will be raised.

- `np.concatenate` returns a new array that is the result of the concatenation. It does not modify the original arrays.

- You can concatenate more than two arrays by passing them as a sequence in the first argument of `np.concatenate`.

In [5]:
import numpy as np

array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2 = np.array([[7, 8, 9], [10, 11, 12]])

np.concatenate((array_1, array_2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
np.concatenate((array_1, array_2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])