## Reshaping

In NumPy, reshaping refers to changing the shape of an array without changing its data. Reshaping allows you to convert an array from one dimension to another, such as converting a 1D array to a 2D array or vice versa. NumPy provides the `reshape` function to perform this operation.

The `reshape` function in NumPy takes the desired shape as an argument and returns a new array with the specified shape. It is important to note that the total number of elements in the original array must be equal to the total number of elements in the reshaped array.

Here's an example to illustrate reshaping:

```python
import numpy as np

# Create a 1D array
array1 = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array to a 2D array with 2 rows and 3 columns
array2 = array1.reshape(2, 3)

print("Original array:")
print(array1)

print("Reshaped array:")
print(array2)
```

Output:
```
Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]
```

In this example, the `reshape` function is used to convert the 1D array `array1` to a 2D array `array2` with 2 rows and 3 columns.

Important notes about reshaping in NumPy:

1. The reshaped array shares the same underlying data buffer with the original array. This means that modifying one array will also affect the other.

2. The `reshape` function returns a new view of the original array whenever possible. However, if the requested shape is not compatible with the original shape, a new copy of the data will be created.

3. When reshaping an array, the total number of elements in the original array must be equal to the total number of elements in the reshaped array. Otherwise, a `ValueError` will be raised.

4. You can use `-1` as one of the dimensions in the shape argument of `reshape` to automatically compute the correct size for that dimension based on the other dimensions and the total number of elements.

5. Reshaping can be performed on arrays of any dimension, not just 1D to 2D or vice versa. For example, you can reshape a 2D array into a 3D array or reshape a 3D array into a 1D array, as long as the total number of elements remains the same.

Reshaping is a powerful operation in NumPy that allows you to transform arrays to match the desired shape for various computations and analyses.

In [2]:
import numpy as np

array_1 = np.array([1, 2, 3, 4, 5, 6])

array_2 = array_1.reshape(2, 3)

print("Original array:")
print(array_1)

print("Reshaped array:")
print(array_2)

Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


> **Note that mutating the reshaped array mutates the original array as well**

In [3]:
array_2[0, 0] = 100

In [4]:
array_1

array([100,   2,   3,   4,   5,   6])