## Universal functions

In NumPy, universal functions, also known as ufuncs, are functions that operate element-wise on ndarrays, allowing for fast and efficient computations. Ufuncs are a key feature of NumPy and provide a convenient way to apply mathematical operations to arrays without the need for explicit loops.

Some common examples of universal functions in NumPy include:

1. Mathematical Functions:
   - `np.abs(arr)`: Compute the absolute value of each element.
   - `np.sqrt(arr)`: Compute the square root of each element.
   - `np.exp(arr)`: Compute the exponential of each element.
   - `np.log(arr)`: Compute the natural logarithm of each element.

2. Arithmetic Operations:
   - `np.add(arr_1, arr_2)` or `np.add(arr_1, scaler)`: Add corresponding elements of two arrays.
   - `np.subtract(arr_1, arr_2)`, `np.subtract(arr_1, scaler)`: Subtract corresponding elements of two arrays.
   - `np.multiply(arr_1, arr_2)`, `np.multiply(arr_1, scaler)`: Multiply corresponding elements of two arrays.
   - `np.divide(arr_1, arr_2)`, `np.divide(arr_1, scaler)`: Divide corresponding elements of two arrays.
   - `np.power(arr_1, arr_2)`, `np.power(arr_1, scaler)`: Raise each element to a specified corresponding power.

3. Aggregation Functions:
   - `np.sum(arr)`: Compute the sum of all elements in an array.
   - `np.mean(arr)`: Compute the arithmetic mean of elements in an array.
   - `np.min(arr)`, `np.max(arr)`: Find the minimum and maximum values in an array, respectively.
   - `np.std(arr)`, `np.var(arr)`: Compute the standard deviation and variance of elements in an array, respectively.

4. Trigonometric Functions:
   - `np.sin(arr)`, `np.cos(arr)`, `np.tan(arr)`: Compute the sine, cosine, and tangent of each element, respectively.
   - `np.arcsin(arr)`, `np.arccos(arr)`, `np.arctan(arr)`: Compute the inverse sine, inverse cosine, and inverse tangent of each element, respectively.

This is not an exhaustive list, but it covers some commonly used universal functions in NumPy. NumPy's documentation provides a comprehensive list of available ufuncs, along with detailed explanations and examples for each function.

### Mathematical functions
1. `np.abs`: The `np.abs` function is used to calculate the absolute values of the elements in an array. It returns an array with the same shape as the input array, where each element is replaced with its absolute value.

   Example:
   ```python
   import numpy as np

   arr = np.array([-2, 4, -6, 8, -10])
   abs_arr = np.abs(arr)
   print(abs_arr)
   ```
   
   Output:
   ```pyhon
   [ 2  4  6  8 10]
   ```

3. `np.sqrt`: The `np.sqrt` function is used to calculate the square root of each element in an array. It returns an array with the same shape as the input array, where each element is replaced with its square root.

   Example:
   ```python
   import numpy as np

   arr = np.array([4, 9, 16, 25, 36])
   sqrt_arr = np.sqrt(arr)
   print(sqrt_arr)
   ```

   Output:
   ```python
   [2. 3. 4. 5. 6.]
   ```

5. `np.exp`: The `np.exp` function is used to calculate the exponential of each element in an array. It returns an array with the same shape as the input array, where each element is replaced with its exponential value.

   Example:
   ```python
   import numpy as np

   arr = np.array([1, 2, 3])
   exp_arr = np.exp(arr)
   print(exp_arr)
   ```

   
   Output:
   ```
   [ 2.71828183  7.3890561  20.08553692]
   ```

6. `np.log`: The `np.log` function is used to calculate the natural logarithm (base e) of each element in an array. It returns an array with the same shape as the input array, where each element is replaced with its natural logarithm.

   Example:
   ```python
   import numpy as np

   arr = np.array([1, 10, 100])
   log_arr = np.log(arr)
   print(log_arr)
   ```

   Output:
   ```python
   [0.         2.30258509 4.60517019]
   ```

These functions are very useful in scientific and mathematical computations, and NumPy provides efficient implementations to perform these operations on arrays of any size.

In [1]:
import numpy as np

arr = np.array([-2, 4, -6, 8, -10])
abs_arr = np.abs(arr)
print(abs_arr)

[ 2  4  6  8 10]


In [3]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081])

In [4]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [5]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229])

### Arithmetic Operations

We have seen arithmetic operations in `NumPy Operations` notebook, here we will talk a little about broadcasting.

#### Broadcasting

Broadcasting between an array and a scalar in NumPy allows the scalar value to be combined with each element of the array in element-wise operations. The scalar is effectively broadcasted to match the shape of the array, enabling the operation to be performed.

Here's how broadcasting between an array and a scalar happens in NumPy:

1. Scalar Expansion: The scalar value is expanded to an array of the same shape as the array it is being combined with. This is done by duplicating the scalar value along all dimensions to match the shape of the array.

2. Element-Wise Operation: Once the scalar and the array have compatible shapes, the element-wise operation is performed between the expanded scalar and the corresponding elements of the array.

Here's an example to illustrate broadcasting between an array and a scalar:

```python
import numpy as np

# Broadcasting example with scalar and array
scalar = 2
array = np.array([1, 2, 3])

# Perform element-wise multiplication
result = scalar * array

print(result)
```

In this example, we have a scalar value `scalar` with the value 2 and an array `array` with shape `(3,)` containing the elements `[1, 2, 3]`. The scalar value is broadcasted to match the shape of the array, resulting in an expanded scalar array `[2, 2, 2]`. Then, the element-wise multiplication is performed between the expanded scalar and the corresponding elements of the array, resulting in the array `result` with the values `[2, 4, 6]`.

The output of the above code will be:
```
[2 4 6]
```

As you can see, the scalar value of 2 was broadcasted to match the shape of the array, allowing the element-wise multiplication to be performed effortlessly.

Broadcasting between an array and a scalar in NumPy is a convenient way to apply scalar operations to all elements of an array without explicitly creating an array of the same shape as the original array. It simplifies the syntax and enhances the efficiency of computations.

In [6]:
import numpy as np

scalar = 2
array = np.array([1, 2, 3])

scalar * array

array([2, 4, 6])

In [7]:
scalar + array

array([3, 4, 5])

In [8]:
scalar / array

array([2.        , 1.        , 0.66666667])

In [9]:
array / scalar

array([0.5, 1. , 1.5])

### Aggregation Functions

1. `np.sum`: The `np.sum` function calculates the sum of all elements in an array or along a specified axis.

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

total_sum = np.sum(arr)
row_sum = np.sum(arr, axis=1)

print(total_sum)  # Output: 21
print(row_sum)    # Output: [6 15]
```

2. `np.mean`: The `np.mean` function computes the arithmetic mean of elements in an array or along a specified axis.

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

mean_value = np.mean(arr)
row_mean = np.mean(arr, axis=1)

print(mean_value)  # Output: 3.5
print(row_mean)    # Output: [2. 5.]
```

3. `np.min`: The `np.min` function returns the minimum value from an array or along a specified axis.

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

min_value = np.min(arr)
row_min = np.min(arr, axis=1)

print(min_value)  # Output: 1
print(row_min)    # Output: [1 4]
```

4. `np.max`: The `np.max` function returns the maximum value from an array or along a specified axis.

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

max_value = np.max(arr)
row_max = np.max(arr, axis=1)

print(max_value)  # Output: 6
print(row_max)    # Output: [3 6]
```

5. `np.std`: The `np.std` function calculates the standard deviation of elements in an array or along a specified axis.

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

std_value = np.std(arr)
row_std = np.std(arr, axis=1)

print(std_value)  # Output: 1.707825127659933
print(row_std)    # Output: [0.81649658 0.81649658]
```

6. `np.var`: The `np.var` function computes the variance of elements in an array or along a specified axis.

```python
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

var_value = np.var(arr)
row_var = np.var(arr, axis=1)

print(var_value)  # Output: 2.9166666666666665
print(row_var)    # Output: [0.66666667 0.66666667]
```

These functions are just a few examples of the many aggregation operations provided by NumPy. They are useful for analyzing and summarizing data in scientific and numerical computations.

In [1]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

total_sum = np.sum(arr)
row_sum = np.sum(arr, axis=1)

print(total_sum)
print(row_sum)

21
[ 6 15]


In [2]:
mean_value = np.mean(arr)
row_mean = np.mean(arr, axis=1)

print(mean_value)
print(row_mean)

3.5
[2. 5.]


In [3]:
max_value = np.max(arr)
row_max = np.max(arr, axis=1)

print(max_value)
print(row_max)

6
[3 6]


In [4]:
std_value = np.std(arr)
row_std = np.std(arr, axis=1)

print(std_value)
print(row_std)

1.707825127659933
[0.81649658 0.81649658]


In [5]:
var_value = np.var(arr)
row_var = np.var(arr, axis=1)

print(var_value)
print(row_var) 

2.9166666666666665
[0.66666667 0.66666667]


### Trigonometric Functions

The trigonometric functions in NumPy (`np.sin`, `np.cos`, `np.tan`, `np.arcsin`, `np.arccos`, `np.arctan`) can be applied to arrays:

1. `np.sin`: When applied to an array, `np.sin` calculates the sine of each element in the array.

Example:
```python
import numpy as np

angles = np.array([0, np.pi/4, np.pi/2])  # Array of angles in radians

sin_values = np.sin(angles)

print(sin_values)
```
Output:
```
[0.         0.70710678 1.        ]
```

2. `np.cos`: When applied to an array, `np.cos` calculates the cosine of each element in the array.

Example:
```python
import numpy as np

angles = np.array([0, np.pi/4, np.pi/2])  # Array of angles in radians

cos_values = np.cos(angles)

print(cos_values)
```
Output:
```
[1.00000000e+00 7.07106781e-01 6.12323400e-17]
```

3. `np.tan`: When applied to an array, `np.tan` calculates the tangent of each element in the array.

Example:
```python
import numpy as np

angles = np.array([0, np.pi/4, np.pi/2])  # Array of angles in radians

tan_values = np.tan(angles)

print(tan_values)
```
Output:
```
[0.00000000e+00 1.00000000e+00 1.63312394e+16]
```

4. `np.arcsin`: When applied to an array, `np.arcsin` calculates the inverse sine of each element in the array and returns an array of corresponding angles in radians.

Example:
```python
import numpy as np

values = np.array([0, 0.5, 1])  # Array of values between -1 and 1

angles = np.arcsin(values)

print(angles)
```
Output:
```
[0.         0.52359878 1.57079633]
```

5. `np.arccos`: When applied to an array, `np.arccos` calculates the inverse cosine of each element in the array and returns an array of corresponding angles in radians.

Example:
```python
import numpy as np

values = np.array([1, 0.5, 0])  # Array of values between -1 and 1

angles = np.arccos(values)

print(angles)
```
Output:
```
[0.         1.04719755 1.57079633]
```

6. `np.arctan`: When applied to an array, `np.arctan` calculates the inverse tangent of each element in the array and returns an array of corresponding angles in radians.

Example:
```python
import numpy as np

values = np.array([0, 1, -1])  # Array of values

angles = np.arctan(values)

print(angles)
```
Output:
```
[ 0.          0.78539816 -0.78539816]
```

In each example, the trigonometric function is applied element-wise to the input array, and the resulting array contains the corresponding values or angles.

In [6]:
import numpy as np

angles = np.array([0, np.pi/4, np.pi/2])  # Array of angles in radians

np.sin(angles)

array([0.        , 0.70710678, 1.        ])

In [7]:
np.cos(angles)

array([1.00000000e+00, 7.07106781e-01, 6.12323400e-17])

In [8]:
np.tan(angles)

array([0.00000000e+00, 1.00000000e+00, 1.63312394e+16])

In [9]:
values = np.array([0, 0.5, 1])

In [10]:
np.arcsin(values)

array([0.        , 0.52359878, 1.57079633])

In [11]:
np.arccos(values)

array([1.57079633, 1.04719755, 0.        ])

In [12]:
np.arctan(values)

array([0.        , 0.46364761, 0.78539816])